config/routes.rb
Rails.application.routes.draw do
  
  get 'actors/new'
  get 'directors/new'
  get 'comments/new'
  get 'sessions/new'
  get 'pages/top'
  root 'pages#top'
  
  resources :users
  resources :movies, only: [:index,:new,:create,:search,:show,:update,:edit,:destroy]
  resources :comments, only: [:create, :new,:update,:destroy]
  resources :directors
  resources :actors
  

  post '/favorites',  to: 'favorites#create'
  delete '/favorites', to: 'favorites#destroy'
  
  get    '/search',                  to: 'movies#search'
  get    '/movies/:id/actor_edit',    to: 'movies#actor_edit'
  patch   '/movies/:id/actor_edit',   to: 'movies#actor_update', as: :actor_create
  
  get    '/login',                   to: 'sessions#new'
  post   '/login',                   to: 'sessions#create'
  delete '/logout',                  to: 'sessions#destroy'
end

app/models/actor.rb
class Actor < ApplicationRecord
  has_many :movie_actors
  has_many :movies, through: :movie_actors
  validates :name, uniqueness: true, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :movie
  
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  
end

app/models/director.rb
class Director < ApplicationRecord
  validates :name, presence: true
  
  has_many :movie_directors
  has_many :movies, through: :movie_directors
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  validates :user, {presence: true}
  validates :comment, {presence: true}
 
  belongs_to :user
  belongs_to :comment
  
  
end

app/models/junle.rb
class Junle < ApplicationRecord
  has_many :movie_junles
  has_many :movies, through: :movie_junles
end

app/models/movie.rb
class Movie < ApplicationRecord
  mount_uploader :image, ImageUploader
  validates :name, presence: true
  
  has_many :comments, dependent: :destroy
  has_many :users, through: :comments
  accepts_nested_attributes_for :comments, allow_destroy: true
 
  has_many :movie_directors, dependent: :destroy
  has_many :directors, through: :movie_directors
  accepts_nested_attributes_for :movie_directors, allow_destroy: true
 
  has_many :movie_junles, dependent: :destroy
  has_many :junles, through: :movie_junles
  accepts_nested_attributes_for :movie_junles, allow_destroy: true
  
  has_many :movie_actors, dependent: :destroy
  has_many :actors, through: :movie_actors
  accepts_nested_attributes_for :movie_actors, allow_destroy: true
  
  
  
  def self.search
    if search
      Movie.where('name LIKE(?)','%#search%')
    else
      Movie.all
    end
  end
  
  def rate_avg
    self.comments.average(:rate)
  end
  
end

app/models/movie_actor.rb
class MovieActor < ApplicationRecord
  belongs_to :movie
  belongs_to :actor
end

app/models/movie_director.rb
class MovieDirector < ApplicationRecord
  belongs_to :movie
  belongs_to :director
end

app/models/movie_junle.rb
class MovieJunle < ApplicationRecord
  belongs_to :movie
  belongs_to :junle
end

app/models/user.rb
class User < ApplicationRecord
  
  VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])[a-z\d]{8,32}+\z/
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates :name, presence: true, length: {maximum: 15}
  validates :email, presence: true, format: {with: VALID_EMAIL_REGEX}
  validates :password, presence: true, format: {with: VALID_PASSWORD_REGEX},length: {minimum: 8,maximum: 32}
  
  has_secure_password
  
  has_many :favorites, dependent: :destroy
  has_many :favorite_comments, through: :favorites,source: :comment
  
  has_many :comments, dependent: :destroy
  has_many :movies, through: :comments
  accepts_nested_attributes_for :comments, allow_destroy: true
end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController
  def new
    @actor = Actor.new
  end
  
  def create
    @actor = Actor.new(actor_params)
    if @actor.save
      redirect_to actors_path
    else
    render :new
    end
  end
  
  def index
    @actors = Actor.all
  end
  
  def edit
    @actor = Actor.find(params[:id])
  end
  
  def update
    @actor = Actor.find(params[:id])
    @actor.update(actor_params)
    redirect_to actors_path
  
  end
  
  def destroy
    @actor = Actor.find(params[:id])
    @actor.destroy
    redirect_to actors_path
  end
  
  private
  def actor_params
    params.require(:actor).permit(:name)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def top
    @movies = Movie.all.order(open_house:'DESC')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user,{only:[:show]}
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path,success: '登録が完了しました'
    else
      flash.now[:danger] = "登録に失敗しました"
      render :new 
    end
  end
  
  def show
    @user = User.find_by(id: current_user.id)
    @movies = @user.movies
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(id:@user.id)
    else
      flash.now[:danger] = "すでに登録されています。"
      render :edit
    end
  end
  
  
  
  private
  def user_params
    params.require(:user).permit(:name, :email,:password, :password_confirmation)
  end
end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/directors_helper.rb
module DirectorsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
  
  def display_open_house(movie)
    if movie.open_house.present?
      movie.open_house.strftime('%Y年%m月%d日')
    else
      "未定"
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/actors/edit.html.erb
<div class = "users-new-wrapper">
  <div class = "container">
    <h1 class = "entry-name">Actor登録</h1>
    <div class = "new-member-entry-form">
      <div class = "row">
        <div class = 'col-md-offset-3 col-md-6' >
          <%= form_for @actor do |f|%>
            <div class = "form-group">
              <%= f.label :name, '俳優名', class: "new-label" %>
              <%= f.text_field :name, class: 'new-form'%>
            </div>
            <%= f.submit "登録", class: "btn-block"%>
          <% end %>
          <%= link_to 'Actor一覧へ', actors_path %>
        </div>
      </div>
    </div>
  </div>
</div> 

app/views/actors/index.html.erb
<div class = "director-index-wrapper">
  <div class = "container">
    <h1>Actor一覧</h1>
    <%= link_to 'Actor入力画面へ', new_actor_path,{class: 'link_info'}%>
    <% @actors.each do |actor|%>
      <div class = "director-index">
        <%= actor.id%>,
        <%= actor.name %>
        <span class = "info-edit">
        <%= link_to '編集する',edit_actor_path(id: actor.id),{method: :get, class: 'd-link-edit'} %>
        <%= link_to '削除する',actor_path(id: actor.id),{method: :delete,class: 'd-link-delete'} %>
        </div>
      </span>
    <% end %>
    <%= link_to 'Actor入力画面へ', new_actor_path,{class: 'link_info'}%>
  </div>
</div>

app/views/actors/new.html.erb
<div class = "users-new-wrapper">
  <div class = "container">
    <h1 class = "entry-name">Actor登録</h1>
    <div class = "new-member-entry-form">
      <div class = "row">
        <div class = 'col-md-offset-3 col-md-6' >
          <%= form_for @actor do |f|%>
            <div class = "form-group">
              <%= f.label :name, '俳優名', class: "new-label" %>
              <%= f.text_field :name, class: 'new-form'%>
            </div>
            <%= f.submit "登録", class: "btn-block"%>
          <% end %>
          <%= link_to 'Actor一覧へ', actors_path %>
        </div>
      </div>
    </div>
  </div>
</div> 

app/views/users/edit.html.erb
<div class = "users-new-wrapper">
  <div class = "container">
    <h1 class = "entry-name">会員登録</h1>
    <div class = "new-member-entry-form">
      <div class = "row">
        <div class = 'col-md-offset-3 col-md-6' >
          <%= form_for @user do |f|%>
            <div class = "form-group">
              <%= f.label :name, '名前（ニックネーム可）', class: "new-label" %>
              <%= f.text_field :name, class: 'new-form'%>
            </div>
            <div class = "form-group">
              <%= f.label :email, 'メールアドレス', class: "new-label" %>
              <%= f.text_field :email, class: 'new-form'%>
            </div>
            <div class = "form-group">
              <%= f.label :password, 'パスワード', class: 'new-label' %>
              <%= f.text_field :password, class: 'new-form' %>
            </div>
            <div class = "form-group">
              <%= f.label :password_confirmation,'パスワード（確認用）', class: "new-label" %>
              <%= f.text_field :password_confirmation, class: 'new-form' %>
            </div>
            <%= f.submit "編集", class: "btn-block"%>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>  

app/views/users/new.html.erb
<div class = "users-new-wrapper">
  <div class = "container">
    <h1 class = "entry-name">会員登録</h1>
    <div class = "new-member-entry-form">
      <div class = "row">
        <div class = 'col-md-offset-3 col-md-6' >
          <%= form_for @user do |f|%>
            <div class = "form-group">
              <%= f.label :name, '名前（ニックネーム可）', class: "new-label" %>
              <%= f.text_field :name, class: 'new-form'%>
            </div>
            <div class = "form-group">
              <%= f.label :email, 'メールアドレス', class: "new-label" %>
              <%= f.text_field :email, class: 'new-form'%>
            </div>
            <div class = "form-group">
              <%= f.label :password, 'パスワード', class: 'new-label' %>
              <%= f.text_field :password, class: 'new-form' %>
            </div>
            <div class = "form-group">
              <%= f.label :password_confirmation,'パスワード（確認用）', class: "new-label" %>
              <%= f.text_field :password_confirmation, class: 'new-form' %>
            </div>
            <%= f.submit "登録", class: "btn-block"%>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>  

app/views/users/show.html.erb
<div class="user-page-wrapper">
  <div class="container">
    <div class="user-name">
      <h1>' <%= @user.name %> 'さんがレビューした映画<%= @movies.count %>件</h1>
    </div>
    
    <div class="user-movie-wrapper">
      <% @movies.each do |movie| %>
        <div class='user-movie'>
          <%= link_to movie_path(id: movie.id) do %>
            <%= image_tag movie.image.url %>
          <% end %>
          <div class='user-movie-name'>
          <%= movie.name %>
          </div>
        </div>
      <% end %>
    </div>
    <div class = 'p-edit'>
      <%= link_to 'プロフィール編集', edit_user_path(id: @user.id), method: :get %>
    </div>
  </div>
</div>