config/routes.rb
Rails.application.routes.draw do
  
  get 'actors/new'
  get 'directors/new'
  get 'comments/new'
  get 'sessions/new'
  get 'pages/top'
  root 'pages#top'
  
  resources :users
  resources :movies, only: [:index,:new,:create,:search,:show,:update,:edit,:destroy]
  resources :comments, only: [:create, :new,:update,:destroy]
  resources :directors
  resources :actors
  

  post '/favorites',  to: 'favorites#create'
  delete '/favorites', to: 'favorites#destroy'
  
  get    '/search',                  to: 'movies#search'
  get    '/movies/:id/actor_edit',    to: 'movies#actor_edit'
  patch   '/movies/:id/actor_edit',   to: 'movies#actor_update', as: :actor_create
  
  get    '/login',                   to: 'sessions#new'
  post   '/login',                   to: 'sessions#create'
  delete '/logout',                  to: 'sessions#destroy'
end

app/models/movie.rb
class Movie < ApplicationRecord
  mount_uploader :image, ImageUploader
  validates :name, presence: true
  
  has_many :comments, dependent: :destroy
  has_many :users, through: :comments
  accepts_nested_attributes_for :comments, allow_destroy: true
 
  has_many :movie_directors, dependent: :destroy
  has_many :directors, through: :movie_directors
  accepts_nested_attributes_for :movie_directors, allow_destroy: true
 
  has_many :movie_junles, dependent: :destroy
  has_many :junles, through: :movie_junles
  accepts_nested_attributes_for :movie_junles, allow_destroy: true
  
  has_many :movie_actors, dependent: :destroy
  has_many :actors, through: :movie_actors
  accepts_nested_attributes_for :movie_actors, allow_destroy: true
  
  
  
  def self.search
    if search
      Movie.where('name LIKE(?)','%#search%')
    else
      Movie.all
    end
  end
  
  def rate_avg
    self.comments.average(:rate)
  end
  
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :authenticate_user,{only:[:new, :create,]}
  before_action :user_admin,{only:[:new,:edit]}
  
  
  def new
    @movie = Movie.new
    @movie.movie_directors.build
    @movie.movie_junles.build 
  end
  def index
    @movies = Movie.all.order(open_house:'DESC').page(params[:page]).per(10)
  end
  
  def search 
    @search_name = params[:search]
    if params[:how_search] == 'movie'
      movie = Movie.where('name like ?', "%#{params[:search]}%")
      @movies = movie.page(params[:page]).per(8)
      
    elsif params[:how_search] == 'cast'
      actors = Actor.where('name like ?', "%#{params[:search]}%")
      if actors.present?
        actor_ids = []
        actors.each {|a| actor_ids.push(a.id)}  
        @movies = Movie.joins(:movie_actors).where('actor_id IN(?)', actor_ids).page(params[:page]).per(8)
      else
        @movies = []
      end
      #@movies = Movie.select('movie.name').joins(:movie_actors,:actors).where(actors.name =>'ダニエル・ラドクリフ')
      
    elsif params[:how_search] == 'user'
      user = User.find_by('name like ?', "%#{params[:search]}%")
      if user.present?
        @movies = user.movies.page(params[:page]).per(8)
      else
        @movies = []
      end
        
    elsif params[:how_search] == 'director'
      directors = Director.where('name like ?', "%#{params[:search]}%")
      if directors.present?
        director_ids = []
        directors.each{ |a| director_ids.push(a.id)}
        @movies = Movie.joins(:movie_directors).where('director_id IN(?)', director_ids).page(params[:page]).per(8)
      else
        @movies = []
      end
    elsif params[:how_search] =='raiting'
      avg = Comment.group(:movie_id).average(:rate)
      rate = params[:rate_search].to_i
      matched_movie_ids = 
      avg.map do |key ,value|
        if value >= rate && value < rate + 1
          key 
        end
      end.compact
      @movies = Movie.where(id: matched_movie_ids).page(params[:page]).per(8)
      @rate_name = rate
      
    elsif params[:how_search] =='junle'
      junle = Junle.find_by('name like ?', "%#{params[:search]}%") 
      @movies= junle.movies.page(params[:page]).per(8)
      #以下q:
    elsif  params[:cast_id].present?
      cast = Actor.find(params[:cast_id])
      @movies = cast.movies.page(params[:page]).per(8)
      @search_name = cast.name
      
    elsif params[:director_id].present?
      director = Director.find(params[:director_id])
      @movies = director.movies.page(params[:page]).per(8)
      @search_name = director.name
      
    elsif params[:junle_id].present?
      junle = Junle.find_by(params[:junle_id])
      @movies = junle.movies.page(params[:page]).per(8)
      @search_name = junle.name
    end
  end
  
  
  
  def create
    @movie = Movie.new(movie_params)
    if @movie.save
      redirect_to movies_path
    else
      render :new
    end
  end
  
  def show 
    @movie = Movie.find_by(id: params[:id])
    @director=Movie.select("directors.name","directors.id").joins(:movie_directors,:directors).find_by(id: params[:id])
    @junle = @movie.junles.first
    @casts = @movie.actors
    @comments = @movie.comments.page(params[:page]).per(10)
    @average = @movie.rate_avg
  end
  
  def edit
    @movie = Movie.find(params[:id])
  end
  
  def update
    @movie = Movie.find(params[:id])
    if @movie.update(movie_params)
      redirect_to movie_path(id: @movie.id)
    else
      render :edit
    end
  end
  
  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    redirect_to root_path
  end
  

  def actor_edit
    @movie = Movie.find(params[:id]) 
    #@movie.movie_actors.find_by(movie_id: @movie.id, actor_id:params[:id]) || @movie.movie_actors.new
  
  end
  
  def actor_update
    @movie = Movie.find(params[:id]) 
    @movie.update_attributes(actor_params)
    redirect_to movie_path(id: @movie.id)
  end
  
  
  # # def actor_update
  # #   @movie = Movie.find(params[:id])
  # #   @movie.movie_actors.find_by(movie_id: @movie.id, actor_id: params[:id])
  # #   actor_params[:actor_ids].each do |id|
  # #     @movie.update_attributes(actor_params)
  # #   end
  #   redirect_to movie_path(id: @movie.id)
  # end
  
  def search_act(search)
    if search
      Actor.where('name like ?', "%#{params[:search]}%")
    else
      Actor.none
    end
  end
  

      
  
  
  private
  def movie_params
    params.require(:movie).permit(:name, :open_house, :running_time, :screen_writer, :image, :summary, movie_junles_attributes: [:id, :junle_id], movie_directors_attributes: [:id, :director_id])
  end
  def actor_params
    if params[:movie]
      params.require(:movie).permit({actor_ids: []}) 
    else
      {actor_ids: []}
    end
  end
end
#avg={6=>0.3e1, 7=>0.35e1, 15=>0.253625011444092e1, 16=>0.35e1}

#matched_movie_ids =
#   avg.each_with_object([]) do |val, array|
#     rate_avg = val[1]
#     rate_search = params[:rate_search].to_i
    
#     if rate_avg >= rate_search && rate_avg < rate_search + 1
#       array << val[0]
#     end
#   end

# @movie = Movie.where(id: matched_movie_ids)

app/helpers/movies_helper.rb
module MoviesHelper
  
  def display_open_house(movie)
    if movie.open_house.present?
      movie.open_house.strftime('%Y年%m月%d日')
    else
      "未定"
    end
  end
end

app/views/movies/actor_edit.html.erb
<div class = "users-new-wrapper">
  <div class = "container">
    <h1><%= @movie.name %>の出演俳優の登録</h1>
    <%= form_with model: @movie,url:actor_create_path(@movie), local:true do |f|%>
    <div class = "new-member-entry-form">
        <%= f.collection_check_boxes(:actor_ids, Actor.all, :id, :name,include_hidden: false) do |c| %>
          <%= c.label {c.check_box + c.text } %>
        <% end %>
      <%= f.submit "追加する", class: "btn-block"%>
    <% end %>
    <%= link_to 'Actor登録', new_actor_path %>
  </div>
</div>

app/views/movies/actor_new.html.erb
<div class = "users-new-wrapper">
  <div class = "container">
    <h1><%= @movie.name %>の出演俳優の登録</h1>
    
    
    <%= form_with model: @movie,url:actor_create_path(@movie), local:true do |f|%>
    <div class = "new-member-entry-form">
        <%= f.collection_check_boxes(:actor_ids, Actor.all, :id, :name,include_hidden: false) do |c| %>
          <%= c.label {c.check_box + c.text } %>
        <% end %>
      <%= f.submit "追加する", class: "btn-block"%>
    <% end %>
    <%= link_to 'Actor登録', new_actor_path %>
  </div>
</div>

app/views/movies/edit.html.erb
<div class = "users-new-wrapper">
  <div class = "container">
    <h1 class = "entry-name"><%= @movie.name %>の編集</h1>
    <div class = "new-member-entry-form">
      <div class = "row">
        <div class = 'col-md-offset-3 col-md-6' >
          <%= form_with model: @movie, local: true do |f|%>
          
            <div class = "form-group">
              <%= f.label :name, '映画名', class: "new-label" %>
              <%= f.text_field :name, class: 'new-form'%>
            </div>
            <div class = "form-group">
              <%= f.label :open_house, '公開日', class: "new-label" %>
              <%= f.date_select :open_house,{use_month_numbers:true,start_year:Time.now.year,end_year:1885,prompt:'選択してください'},{class: 'date-new-form'} %>
            </div>
            <div class = "form-group">
              <%= f.label :running_time, '上映時間', class: "new-label" %>
              <%= f.text_field :running_time, class: 'new-form' %>
            </div>
            <div class = "form-group">
              <%= f.label :director_id,'監督', class: 'new-label' %>
              <%= f.fields_for :movie_directors, @movie.movie_directors do |director| %>
                <%= director.collection_select :director_id, Director.all, :id, :name, include_blank: '選択してください', class: 'new-form' %>
              <% end %>
            </div>
            <div class = "form-group">
              <%= f.label :screen_writer,'脚本家', class: 'new-label' %>
              <%= f.text_field :screen_writer, class: 'new-form' %>
            </div>
            <div class = "form-group">
              <%= f.label :summary,'あらすじ', class: "new-label" %>
              <%= f.text_area :summary, class: 'new-area' %>
            </div>
            <div class = "form-group">
              <%= f.label :junle_id,'ジャンル', class: "new-label" %>
              <%= f.fields_for :movie_junles, @movie.movie_junles do |junle| %>
                <%= junle.collection_select :junle_id, Junle.all, :id, :name, include_blank: "選択してください", class: 'new-form' %>
              <% end %>
            </div>
            <div class = "form-group">
              <%= f.label :image,'画像', class: "new-label" %>
              <%= f.file_field :image, class: 'new-form' %>
            </div>
            <%= f.submit "編集", class: "btn-block"%>
          <% end %>
          <div class = 'info-add'>
            <%= link_to 'director登録', new_director_path %>
            <%= link_to 'Actor登録', "/movies/#{@movie.id}/actor_edit" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>  

app/views/movies/index.html.erb
<div class = "index-wrapper">
  <div class = 'container'>
    <% @movies.each do |movie| %>
        <div class = "index-wrapper-up">
          <div class = "index-image">
          <%= link_to movie_path(id: movie.id) do %>
            <% if movie.image.present? %>
              <%= image_tag movie.image.url %> 
            <% else %>
              <div class = "empty-img"></div>
            <% end %>
          <% end %>
          </div>
          <div class = "index-description">
            <h1 class = "index-name">
              <%= movie.name %>
            </h1>
            <span class= "index-open-house">
              <% if movie.image.present? %>
              上映日:<%= movie.open_house.strftime('%Y年%m月%d日') %>
              <% end %>
            </span>
            /
            <span class = "index-time">
              上映時間:<%= movie.running_time %>分
            </span>
            <div>
            <span class = "index-junle">
              ジャンル:
              <% movie.junles.each do |junle| %>
              <%= junle.name %>
              <% end %>
            </spam>
            /
            <span class = "index-director">
              監督:
              <% movie.directors.each do |director| %>
              <%= director.name %>
              <% end %>
            </span>
            </div>
            <div class = index-summary>あらすじ:</div>
            <p class = "index-movie-summary">
              <%= movie.summary %>
            </p>
          </div>
        </div>
    <% end %>
    <%= paginate @movies %>
  </div>
</div>

app/views/movies/new.html.erb
<div class = "users-new-wrapper">
  <div class = "container">
    <h1 class = "entry-name">映画情報登録</h1>
    <div class = "new-member-entry-form">
      <div class = "row">
        <div class = 'col-md-offset-3 col-md-6' >
          <%= form_with model: @movie, local: true do |f|%>
          
            <div class = "form-group">
              <%= f.label :name, '映画名', class: "new-label" %>
              <%= f.text_field :name, class: 'new-form'%>
            </div>
            <div class = "form-group">
              <%= f.label :open_house, '公開日', class: "new-label" %>
              <%= f.date_select :open_house,{use_month_numbers:true,start_year:Time.now.year,end_year:1885,prompt:'選択してください'},{class: 'date-new-form'} %>
            </div>
            <div class = "form-group">
              <%= f.label :running_time, '上映時間', class: "new-label" %>
              <%= f.text_field :running_time, class: 'new-form' %>
            </div>
            <div class = "form-group">
              <%= f.label :director_id,'監督', class: 'new-label' %>
              <%= f.fields_for :movie_directors, @movie.movie_directors do |director| %>
                <%= director.collection_select :director_id, Director.all, :id, :name, include_blank: '選択してください', class: 'new-form' %>
              <% end %>
              <%= link_to 'director登録', new_director_path %>
            </div>
            <div class = "form-group">
              <%= f.label :screen_writer,'脚本家', class: 'new-label' %>
              <%= f.text_field :screen_writer, class: 'new-form' %>
            </div>
            <div class = "form-group">
              <%= f.label :summary,'あらすじ', class: "new-label" %>
              <%= f.text_area :summary, class: 'new-area' %>
            </div>
            <div class = "form-group">
              <%= f.label :junle_id,'ジャンル', class: "new-label" %>
              <%= f.fields_for :movie_junles, @movie.movie_junles do |junle| %>
                <%= junle.collection_select :junle_id, Junle.all, :id, :name, include_blank: "選択してください", class: 'new-form' %>
              <% end %>
            </div>
            
            <div class = "form-group">
              <%= f.label :image,'画像', class: "new-label" %>
              <%= f.file_field :image, class: 'new-form' %>
            </div>
            <%= f.submit "登録", class: "btn-block"%>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>  

app/views/movies/search.html.erb
<div class = "search-result-wrapper">
  <div class = "container">
    <% if @movies.present? %>
      <% if params[:how_search] =='raiting' %>
        <h1 class = "search-name">'星<%= @rate_name %>個以上'でヒットした映画 <%= @movies.count %>件</h1>
      <% else %>
        <h1 class = "search-name">'<%= @search_name %>' でヒットした映画 <%= @movies.count %>件</h1>
      <% end %>
      <div class = "search-result">
        <% @movies[0..11].each do |movie| %>
          <%= link_to movie_path(id: movie.id) do %>
            <div class = "search-result-index">
              <%= image_tag movie.image.url %>
              <h1><%= movie.name %></h1>
            </div>
          <% end %>
        <% end %>
        <%= paginate @movies %>
      </div>
    <% elsif @movies = nil%> 
      <div class = "no-hit">
        <p>ヒットしませんでした</p>
      </div>
    <% else %>
      <div class = "no-hit">
        <p>ヒットしませんでした</p>
      </div>
    <% end %>
  </div>
</div>

app/views/movies/show.html.erb
<div class="show-wrapper">
  <div class="container">
    
    <div class="show-movie-wrapper">
      <div class="show-movie-upper-img">
        <% if @movie.image.present? %>
        <%= image_tag @movie.image.url %>
        <% end %>
      </div>
      
      <div class="show-movie-upper-details">
        <h1 class="detail-name"><%= @movie.name%></h1>
        <span class="detail-open-house">上映日: <%= display_open_house(@movie) %></span>
        /
        <span class='detail-ranning-time'>上映時間: <%= @movie.running_time %>分</span>
        <br>
        <% if @junle.present? %>
          <%= link_to search_path(junle_id: @junle.id) do %>
            <span class="detail-junle">ジャンル: <%= @junle.name %></span>
          <% end %>
        <% end %>
        /
        <% if @director.present? %>
          <%= link_to search_path(director_id: @director.id) do %>
            <span class='detail-director'>監督: <%= @director.name %></span>
          <% end %>
        <% end %>
        /
        <% if @casts != nil %>
          <span class='detail-screen-writer'>脚本家: <%= @movie.screen_writer%></span>
          <h4 class = "cast">キャスト: </h4>
          <% @casts.each do |cast| %>
            <%= link_to search_path(cast_id: cast.id) do %>
              <span class='detail-cast'><%= cast.name %></span>
            <% end %>
          <% end %>
        <% end %>
        <div class="avg">
          <div class="star-raty-avg" id="star-rate-avg<%= @movie.id %>">
          </div>
          <% if @average != nil%>
            <div class='star-rate-avg-score'>
              <%= @average.round(1) %>
            </div>
          <% end %>
        </div>
          <script>
          $(document).on('turbolinks:load', function(){
            let children = $('#star-rate-avg<%= @movie.id %> img')
            if (children.length > 0) {return}
            $('#star-rate-avg<%= @movie.id %>').raty({
              size: 36,
              number: 5,
              starOff:  '<%= asset_path('star-off.png') %>',
              starOn:'<%= asset_path('star-on.png') %>',
              starHalf: '<%= asset_path('star-half.png') %>',
              half: true,
              readOnly: true,
              score: <%= @average %>
            });
          });
          </script>
          
        <p class = 'summary-name'>あらすじ:</p>
        <p class='detail-summary'><%= @movie.summary %></p>
        <div class='movie-show-link'>
          <i class="far fa-share-square"></i>
          <%= link_to 'この映画をレビューする', new_comment_path(id: @movie.id), method: :get %>
          <% if logged_in? && current_user.admin? %>
            <%= link_to 'この映画を編集する',edit_movie_path(id: @movie.id), method: :get %>
            <%= link_to 'この映画を削除する',movie_path(id: @movie.id),{method: :delete} %>
            <div >
              <%= link_to 'この映画のキャストを登録する',"/movies/#{@movie.id}/actor_edit"%>
            </div>
          <% end %>
          <div>
          </div>
        </div>
      </div>
    </div>
    
    <h1 class="movie-comment">この映画に関するコメント</h1>
    <% @comments.each do |comment| %>
      <div class=comment-index-wrapper>
        <div class="comment-upper">
          <div class="comment-upper-left">
            <div class="comment-name">
              <h3><%= comment.user.name %>さんのコメント</h3>
            </div>
            <div class="comment-update">
              <%= comment.updated_at.strftime('%Y年%m月%d日%H時%M分') %>
            </div>
          </div>
          <div class="star-raty" id="star-rate-<%= comment.id %>">
          </div>
          <div class="star-rate-score"><%= comment.rate.round(1) %>
          </div>
          <script>
          $(function() {
            let children = $('#star-rate-<%= comment.id %> img')
            if (children.length > 0) {return}
            $('#star-rate-<%= comment.id %>').raty({
              size: 36,
              number: 5,
              starOff:  '<%= asset_path('star-off.png') %>',
              starOn:'<%= asset_path('star-on.png') %>',
              starHalf: '<%= asset_path('star-half.png') %>',
              half: true,
              readOnly: true,
              score: <%= comment.rate %>
            });
          });
          </script>
        </div>
        
        <div class="comment-text">
          <p><%= comment.comment %></p>
        </div>
        
        <div class="iine">
          <% if !comment.favorite_users.include?(current_user) %>
            <%= link_to favorites_path(id: comment.id), method: :post do %>
              <i class="far fa-heart topic-index-icon like-btn" aria-hidden="true"></i>
            <% end %>
          <% else %>
            <%= link_to favorites_path(id: comment.id), method: :delete do %>
              <i class="far fa-heart topic-index-icon unlike-btn" aria-hidden="true"></i>
            <% end %>
          <% end %>
          <div class="favorite-user-count">
            いいね！<%= comment.favorite_users.count %>
            <% if logged_in? && comment.user_id == current_user.id %>
              <div class = "destroy-btn"> 
                <i class="far fa-share-square"></i>
                <%= link_to '削除する', comment_path(id: comment.id), {method: :delete} %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
    
    
  <%= paginate @comments %>
  </div>
</div>