config/routes.rb
Rails.application.routes.draw do
  
  get 'actors/new'
  get 'directors/new'
  get 'comments/new'
  get 'sessions/new'
  get 'pages/top'
  root 'pages#top'
  
  resources :users
  resources :movies, only: [:index,:new,:create,:search,:show,:update,:edit,:destroy]
  resources :comments, only: [:create, :new,:update,:destroy]
  resources :directors
  resources :actors
  

  post '/favorites',  to: 'favorites#create'
  delete '/favorites', to: 'favorites#destroy'
  
  get    '/search',                  to: 'movies#search'
  get    '/movies/:id/actor_edit',    to: 'movies#actor_edit'
  patch   '/movies/:id/actor_edit',   to: 'movies#actor_update', as: :actor_create
  
  get    '/login',                   to: 'sessions#new'
  post   '/login',                   to: 'sessions#create'
  delete '/logout',                  to: 'sessions#destroy'
end

app/models/actor.rb
class Actor < ApplicationRecord
  has_many :movie_actors
  has_many :movies, through: :movie_actors
  validates :name, uniqueness: true, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :movie
  
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  
end

app/models/director.rb
class Director < ApplicationRecord
  validates :name, presence: true
  
  has_many :movie_directors
  has_many :movies, through: :movie_directors
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  validates :user, {presence: true}
  validates :comment, {presence: true}
 
  belongs_to :user
  belongs_to :comment
  
  
end

app/models/junle.rb
class Junle < ApplicationRecord
  has_many :movie_junles
  has_many :movies, through: :movie_junles
end

app/models/movie.rb
class Movie < ApplicationRecord
  mount_uploader :image, ImageUploader
  validates :name, presence: true
  
  has_many :comments, dependent: :destroy
  has_many :users, through: :comments
  accepts_nested_attributes_for :comments, allow_destroy: true
 
  has_many :movie_directors, dependent: :destroy
  has_many :directors, through: :movie_directors
  accepts_nested_attributes_for :movie_directors, allow_destroy: true
 
  has_many :movie_junles, dependent: :destroy
  has_many :junles, through: :movie_junles
  accepts_nested_attributes_for :movie_junles, allow_destroy: true
  
  has_many :movie_actors, dependent: :destroy
  has_many :actors, through: :movie_actors
  accepts_nested_attributes_for :movie_actors, allow_destroy: true
  
  
  
  def self.search
    if search
      Movie.where('name LIKE(?)','%#search%')
    else
      Movie.all
    end
  end
  
  def rate_avg
    self.comments.average(:rate)
  end
  
end

app/models/movie_actor.rb
class MovieActor < ApplicationRecord
  belongs_to :movie
  belongs_to :actor
end

app/models/movie_director.rb
class MovieDirector < ApplicationRecord
  belongs_to :movie
  belongs_to :director
end

app/models/movie_junle.rb
class MovieJunle < ApplicationRecord
  belongs_to :movie
  belongs_to :junle
end

app/models/user.rb
class User < ApplicationRecord
  
  VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])[a-z\d]{8,32}+\z/
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates :name, presence: true, length: {maximum: 15}
  validates :email, presence: true, format: {with: VALID_EMAIL_REGEX}
  validates :password, presence: true, format: {with: VALID_PASSWORD_REGEX},length: {minimum: 8,maximum: 32}
  
  has_secure_password
  
  has_many :favorites, dependent: :destroy
  has_many :favorite_comments, through: :favorites,source: :comment
  
  has_many :comments, dependent: :destroy
  has_many :movies, through: :comments
  accepts_nested_attributes_for :comments, allow_destroy: true
end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/directors_helper.rb
module DirectorsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
  
  def display_open_house(movie)
    if movie.open_house.present?
      movie.open_house.strftime('%Y年%m月%d日')
    else
      "未定"
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width,initial-scale=1.0,minimum-scale=1.0">
    <title>Choim</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "https://use.fontawesome.com/releases/v5.6.1/css/all.css" %>
    <%= stylesheet_link_tag "https://fonts.googleapis.com/css2?family=Lato:wght@400;700&family=Noto+Sans+JP:wght@400;700&display=swap" %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>
  <body>
    <header>
      <div class = 'header-wrapper'>
        <div class = "header-up">
          <ul class = "menu-up">
            <% if logged_in? %>
              <% if current_user.admin? %>
                <li class = "menu-logout">
                  <%= link_to '映画情報登録', new_movie_path %>
                </li>
              <% else %>
                <li class = 'menu-logout'>
                  <%= current_user.name %>さん
                </li>
              <% end %>
              <li class = "menu-logout">
                <%= link_to 'マイページ', user_path(id: current_user.id) %>
              </li>
              <li class = "menu-end-logout">
                <%= link_to 'ログアウト', logout_path, method: :delete,data: {confirm: '本当にログアウトしますか？'} %>
              </li>
            <% else %>
              <li class = "menu-right">
                <%= link_to '新規USER', new_user_path %>
              </li>
              <li class = "menu-right">
                <%= link_to 'ログイン', login_path %>
              </li>
              <li class = "menu-right-end">
                <%= link_to 'top', root_path %>
              </li>
            <% end %>
          </ul>
        </div>
        <div class = "header-down">
          <%= link_to image_tag('rogo2.png', class:'rogo-img'), root_path %>
          <div class = "search-form-wrapper">
            <%= form_with(url: search_path, method: :get, local: true) do |f| %>
              <div class = "search-wrapper">
                <%= f.text_field :search, class: 'search-form', id: 'search-1' %>
                <%= f.select :rate_search, @list, {include_blank:'選択してください'}, {class: 'search-form',id: 'search-2'} %>
                <ul class = "menu-down-left"> 
                  <li onclick=formSwitch()><%= f.radio_button :how_search, 'movie' ,checked: true %><%= f.label(:how_search, '映画検索', value: 'movie') %></li>
                  <li onclick=formSwitch()><%= f.radio_button :how_search, 'cast' %><%= f.label(:how_search, 'CAST検索', value: 'cast') %></li>
                  <li onclick=formSwitch()><%= f.radio_button :how_search, 'user' %><%= f.label(:how_search, 'USER検索', value: 'user') %></li>
                </ul>
                <ul class = "menu-down-right">
                  <li onclick=formSwitch()><%= f.radio_button :how_search, 'director' %><%= f.label(:how_search, '監督検索', value: 'director') %></li>
                  <li onclick=formSwitch()><%= f.radio_button :how_search, 'raiting' %><%= f.label(:how_search, '評価検索', value: 'raiting') %></li>
                  <li onclick=formSwitch()><%= f.radio_button :how_search, 'junle' %><%= f.label(:how_search, 'ジャンル検索', value: 'junle') %></li>
                </ul>
                <div class = "btn-wrapper">
                  <%= f.submit :検索, class: 'search-btn'%>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
      <script>
         function formSwitch() {
          radio = document.getElementsByName('how_search')
          if (radio[4].checked) {
            document.getElementById('search-1').style.display = "none";
            document.getElementById('search-2').style.display = "";
          } else {
            document.getElementById('search-1').style.display = "";
            document.getElementById('search-2').style.display = "none";
          } 
        }
         window.addEventListener('load', formSwitch());
      </script>
      
    </header>
 
    <%= yield %>
    <footer>
      <div class = "footer">
    </footer>
  </body>
</html>

app/views/pages/top.html.erb
<body>
<div class = top-wrapper>
    <div class = "main">
        <%=image_tag 'main04.jpg' %>
        <p>Choim</p>
    </div>
    <div class = "container">
      <div class = "topic-movie">
        <p>現在話題の映画</p>
      </div>
      <div class = "top-index-wrapper">
        <% @movies[0..11].each do | movie | %>
          <%= link_to movie_path(id: movie.id) do %>
            <div class="movie-index-wrapper">
              <div class="movie-index">
                <%= image_tag movie.image.url %>
                <h1 class="movie-index-name">
                <%= movie.name %>
                </h1>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    <div class = "movie-index-link">
      <h1><%= link_to "映画一覧へ", movies_path %></h1>
    </div>
  </div>
</div>


</body>